# Generated by Django 5.2.4 on 2025-09-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('localidad', 'provincia')},
        ),
    ]
