# Generated by Django 5.2.4 on 2025-09-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_localidad_unique_together'),
        ('expediente', '0003_rol_alter_expediente_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
