# Generated by Django 5.2.4 on 2025-09-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_expediente', models.CharField(max_length=100, verbose_name='Estado el expediente')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado del expediente',
                'verbose_name_plural': 'Estado de los expedientes',
            },
        ),
        migrations.CreateModel(
            name='GrupoEtario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_etario', models.CharField(max_length=50, verbose_name='Grupo Etario')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo Etario',
                'verbose_name_plural': 'Grupos etarios',
            },
        ),
        migrations.CreateModel(
            name='MedioIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_ingreso', models.CharField(max_length=50, verbose_name='Medio de Ingreso')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medio de Ingreso',
                'verbose_name_plural': 'Medios de Ingresos',
            },
        ),
        migrations.CreateModel(
            name='ResumenIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_intervencion', models.CharField(max_length=50, verbose_name='Resumen de Intervención')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resumen de Intervención',
                'verbose_name_plural': 'Resumenes de intervenciones',
            },
        ),
        migrations.CreateModel(
            name='TipoPatrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_patrocinio', models.CharField(max_length=50, verbose_name='Tipo de Patrocinio')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de patrocinio',
                'verbose_name_plural': 'Tipos de patrocinios',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(max_length=50, verbose_name='Tipo de Solicitud')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de solicitud',
                'verbose_name_plural': 'Tipos de solicitudes',
            },
        ),
    ]
