# Generated by Django 5.2.4 on 2025-09-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('expediente', '0001_initial'),
        ('institucion', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de expediente')),
                ('anio', models.PositiveIntegerField(default=2025, verbose_name='Año del expediente')),
                ('abreviatura', models.CharField(max_length=4, verbose_name='Abreviatura')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('identificador', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Identificador del expediente')),
                ('fecha_de_juzgado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Juzgado')),
                ('fecha_de_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('cuij', models.CharField(blank=True, max_length=50, null=True, verbose_name='CUIJ')),
                ('clave_sisfe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave SISFE')),
                ('expediente_fisico', models.BooleanField(default=False)),
                ('edad_persona', models.PositiveIntegerField(blank=True, null=True)),
                ('situacion_habitacional_hist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situación habitacional historica')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaviones')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('estado_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_estado_expediente', to='expediente.estadoexpediente')),
                ('grupo_etario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_grupo_etario', to='expediente.grupoetario')),
                ('medio_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.medioingreso')),
                ('resumen_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.resumenintervencion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sede', verbose_name='Sede')),
                ('tipo_patrocinio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.tipopatrocinio')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.tiposolicitud')),
            ],
            options={
                'ordering': ['-anio', '-numero'],
                'unique_together': {('numero', 'anio', 'abreviatura')},
            },
        ),
        migrations.CreateModel(
            name='ExpedienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='documentos/expedientes/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteinstitucion_expediente', to='expediente.expediente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteinstitucion_institucion', to='institucion.institucion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteinstitucion_rol', to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedientePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepersona_expediente', to='expediente.expediente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepersona_persona', to='persona.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepersona_rol', to='core.rol')),
            ],
        ),
    ]
