# Generated by Django 5.2.4 on 2025-09-15 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_localidad_unique_together'),
        ('expediente', '0002_expediente_expedientedocumento_expedienteinstitucion_and_more'),
        ('institucion', '0001_initial'),
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='estado_expediente',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='grupo_etario',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='medio_ingreso',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='resumen_intervencion',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='tipo_patrocinio',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='tipo_solicitud',
        ),
        migrations.AlterField(
            model_name='expedienteinstitucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientejudicial_institucion', to='institucion.institucion'),
        ),
        migrations.AlterField(
            model_name='expedientepersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepresencial_persona', to='persona.persona'),
        ),
        migrations.CreateModel(
            name='ExpedienteJudicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de expediente')),
                ('anio', models.PositiveIntegerField(default=2025, verbose_name='Año del expediente')),
                ('abreviatura', models.CharField(max_length=4, verbose_name='Abreviatura')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('identificador', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Identificador del expediente')),
                ('edad_persona', models.PositiveIntegerField(blank=True, null=True)),
                ('situacion_habitacional_hist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situación habitacional historica')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaviones')),
                ('fecha_juzgado', models.DateField(blank=True, null=True, verbose_name='Fecha en que el juzgado toma conocimiento')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción del expediente judicial')),
                ('cuij', models.CharField(blank=True, max_length=100, null=True, verbose_name='CUIJ')),
                ('clave_sisfe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave SISFE')),
                ('expediente_fisico', models.BooleanField(default=False, verbose_name='¿Tiene expediente físico?')),
                ('estado_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judicial_estado_expediente', to='expediente.estadoexpediente')),
                ('grupo_etario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judicial_grupo_etario', to='expediente.grupoetario')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion')),
                ('medio_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.medioingreso')),
                ('resumen_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.resumenintervencion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sede', verbose_name='Sede')),
                ('tipo_patrocinio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.tipopatrocinio')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.tiposolicitud')),
            ],
            options={
                'ordering': ['-anio', '-numero'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='expedienteinstitucion',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientejudicial_expediente', to='expediente.expedientejudicial'),
        ),
        migrations.CreateModel(
            name='ExpedienteJudicialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='documentos/judicial/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.expedientejudicial')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de expediente')),
                ('anio', models.PositiveIntegerField(default=2025, verbose_name='Año del expediente')),
                ('abreviatura', models.CharField(max_length=4, verbose_name='Abreviatura')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('identificador', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Identificador del expediente')),
                ('edad_persona', models.PositiveIntegerField(blank=True, null=True)),
                ('situacion_habitacional_hist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situación habitacional historica')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaviones')),
                ('fecha_juzgado', models.DateField(blank=True, null=True, verbose_name='Fecha en que el juzgado toma conocimiento')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción del expediente judicial')),
                ('cuij', models.CharField(blank=True, max_length=100, null=True, verbose_name='CUIJ')),
                ('clave_sisfe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave SISFE')),
                ('expediente_fisico', models.BooleanField(default=False, verbose_name='¿Tiene expediente físico?')),
                ('estado_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_estado_expediente', to='expediente.estadoexpediente')),
                ('grupo_etario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficio_grupo_etario', to='expediente.grupoetario')),
                ('medio_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.medioingreso')),
                ('resumen_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.resumenintervencion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sede', verbose_name='Sede')),
                ('tipo_patrocinio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.tipopatrocinio')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.tiposolicitud')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteoficio_usuario_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anio', '-numero'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpedienteOficioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='documentos/oficio/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.expedienteoficio')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedientePresencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de expediente')),
                ('anio', models.PositiveIntegerField(default=2025, verbose_name='Año del expediente')),
                ('abreviatura', models.CharField(max_length=4, verbose_name='Abreviatura')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('identificador', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Identificador del expediente')),
                ('edad_persona', models.PositiveIntegerField(blank=True, null=True)),
                ('situacion_habitacional_hist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Situación habitacional historica')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaviones')),
                ('estado_expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencial_estado_expediente', to='expediente.estadoexpediente')),
                ('grupo_etario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencial_grupo_etario', to='expediente.grupoetario')),
                ('medio_ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.medioingreso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('resumen_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.resumenintervencion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sede', verbose_name='Sede')),
                ('tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.tiposolicitud')),
            ],
            options={
                'ordering': ['-anio', '-numero'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='expedientepersona',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepresencial_expediente', to='expediente.expedientepresencial'),
        ),
        migrations.CreateModel(
            name='ExpedientePresencialDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='documentos/presencial/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expediente.expedientepresencial')),
            ],
        ),
        migrations.AlterField(
            model_name='expedienteinstitucion',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientejudicial_rol', to='expediente.rol'),
        ),
        migrations.AlterField(
            model_name='expedientepersona',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientepresencial_rol', to='expediente.rol'),
        ),
        migrations.DeleteModel(
            name='ExpedienteDocumento',
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
    ]
