# Generated by Django 5.2.4 on 2025-09-15 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_rol_alter_expediente_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteOficioso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteoficioso_expediente', to='expediente.expedienteoficio')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteoficioso_rol', to='expediente.rol')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedienteoficioso_usuario_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
